# This is a basic workflow that is manually triggered #

name: Cypress nightly split
run-name: "Cypress [${{ inputs.browser || 'chrome' }}] - Spec: ${{ inputs.spec || 'all' }} - Split: ${{  matrix.split_index }} / ${{  matrix.split_total }} "
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to use'
        required: false
        default: 'chrome'
        type: choice
        options:
          - chrome
          - electron
          - firefox
      spec:
        description: 'Spec pattern or single file to run (leave empty for full suite)'
        required: false
        default: ''
        type: string
#  schedule:
#    - cron: '42 0 * * 1,2,3,4,5,6'
#      timezone: 'Europe/Paris'
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    name: "split ${{ matrix.split_index }}"
    strategy:
      fail-fast: false
      matrix:
        # Runs 3 parallel jobs for chunk 0, 1, and 2
        split_total: [4]
        split_index: [0, 1, 2, 3]
    steps:

      - uses: actions/checkout@v7

      - name: Install dependencies
        run: npm install

      - name: Cypress on Chrome
        uses: cypress-io/github-action@v7
        with:
          config-file: cypress.config-github.ts
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
          browser: ${{ inputs.browser || 'chrome' }}
          spec: ${{ inputs.spec }}
          quiet: true
        env:
          # If split_total is not defined, SPLIT is empty and cypress-split runs all specs without splitting
          SPLIT: ${{ matrix.split_total }}
          SPLIT_INDEX: ${{ matrix.split_index }}
          SPLIT_SUMMARY: 'false'  # Suppresses the 166-row table

          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # ic3 related environment variables
          CYPRESS_ic3_user: ${{ secrets.IC3_USER }}
          CYPRESS_ic3_password: ${{ secrets.IC3_PASSWORD }}
          CYPRESS_GITHUB_ACTIONS: true
          CYPRESS_NO_PASSING: true
